export interface CurrencyNames {
  Key: string;
  Value: string;
}

export const CURRENCY_NAMES: CurrencyNames[] = [
  { Key: 'KWD', Value: 'Dinar kuwaití' },
  { Key: 'OMR', Value: 'Rial omaní' },
  { Key: 'JOD', Value: 'Dinar jordano' },
  { Key: 'GBP', Value: 'Libra esterlina' },
  { Key: 'EUR', Value: 'Euro' },
  { Key: 'CHF', Value: 'Franco suizo' },
  { Key: 'USD', Value: 'Dólar estadounidense' },
  { Key: 'CAD', Value: 'Dólar canadiense' },
  { Key: 'AUD', Value: 'Dólar australiano' },
  { Key: 'SGD', Value: 'Dólar de Singapur' },
  { Key: 'NZD', Value: 'Dólar neozelandés' },
  { Key: 'BGN', Value: 'Lev búlgaro' },
  { Key: 'FJD', Value: 'Dólar fiyiano' },
  { Key: 'TND', Value: 'Dinar tunecino' },
  { Key: 'LTL', Value: 'Litas lituana' },
  { Key: 'PEN', Value: 'Sol peruano' },
  { Key: 'ILS', Value: 'Nuevo séquel israelí' },
  { Key: 'QAR', Value: 'Rial catarí' },
  { Key: 'AED', Value: 'Dírham de los Emiratos Árabes Unidos' },
  { Key: 'SAR', Value: 'Rial saudí' },
  { Key: 'PLN', Value: 'Esloti polaco' },
  { Key: 'BRL', Value: 'Real brasileño' },
  { Key: 'RON', Value: 'Leu rumano' },
  { Key: 'MYR', Value: 'Ringgit malayo' },
  { Key: 'TRY', Value: 'Lira turca' },
  { Key: 'DKK', Value: 'Corona danesa' },
  { Key: 'CNY', Value: 'Yuan chino' },
  { Key: 'HKD', Value: 'Dólar de Hong Kong' },
  { Key: 'NOK', Value: 'Corona noruega' },
  { Key: 'SEK', Value: 'Corona sueca' },
  { Key: 'MAD', Value: 'Dírham marroquí' },
  { Key: 'ZAR', Value: 'Rand sudafricano' },
  { Key: 'EGP', Value: 'Libra egipcia' },
  { Key: 'MXN', Value: 'Peso mexicano' },
  { Key: 'CZK', Value: 'Corona checa' },
  { Key: 'ARSBSR', Value: 'Peso Argentino' },
  { Key: 'ARS', Value: 'Peso Argentino' },
  { Key: 'TWD', Value: 'Nuevo dólar taiwanés' },
  { Key: 'THB', Value: 'Baht tailandés' },
  { Key: 'BEF', Value: 'Franco belga' },
  { Key: 'MUR', Value: 'Rupia de Mauricio' },
  { Key: 'PHP', Value: 'Peso filipino' },
  { Key: 'RUB', Value: 'Rublo ruso' },
  { Key: 'INR', Value: 'Rupia india' },
  { Key: 'XPF', Value: 'Franco CFP' },
  { Key: 'ISK', Value: 'Corona islandesa' },
  { Key: 'JPY', Value: 'Yen japonés' },
  { Key: 'AMD', Value: 'Dram armenio' },
  { Key: 'XAF', Value: 'Franco CFA de África Central' },
  { Key: 'CLP', Value: 'Peso chileno' },
  { Key: 'KRW', Value: 'Won surcoreano' },
  { Key: 'COP', Value: 'Peso colombiano' },
  { Key: 'PYG', Value: 'Guaraní paraguayo' },
  { Key: 'IDR', Value: 'Rupia indonesia' },
  { Key: 'VND', Value: 'Dong vietnamita' },
  { Key: 'TRL', Value: 'Lira turca' }
];
